apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ecr-full-access
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_DEFAULT_REGION: ap-northeast-2

---
apiVersion: v1
metadata:
  name: ecr-secret
data:
  .dockerconfigjson: {{ "{}" | b64enc }}
kind: Secret
type: kubernetes.io/dockerconfigjson

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-refresh-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ecr-secret"]
  verbs: ["patch"]