apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: devops-tools
spec:
  schedule: "0 */10 * * *" # 10시간마다 실행
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-secret-refresh
          containers:
            - name: ecr-secret-refresh
              image: ubuntu:latest
              command:
                - /bin/bash
                - -c
                - |
                  chmod +x /scripts/refresh-ecr-secret.sh
                  /scripts/refresh-ecr-secret.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
                - name: aws-config
                  mountPath: /root/.aws/config
                  subPath: config
                - name: aws-credentials
                  mountPath: /root/.aws/credentials
                  subPath: credentials
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: ecr-secret-refresh-script
                defaultMode: 0777 # ConfigMap Read-Only FileSystem Error Solution
            - name: aws-config
              secret:
                secretName: ecr-config
            - name: aws-credentials
              secret:
                secretName: ecr-credential
