apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prod
  name: redis-config
data:
  redis-config: |
    maxmemory 270mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  namespace: prod
  name: redis
  labels:
    app: redis
spec:
  nodeSelector:
    node-type: ondemand
  containers:
    - name: redis
      image: redis:latest
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      resources:
        requests:
          cpu: 32m
          memory: 128Mi
        limits:
          cpu: 64m
          memory: 256Mi
      ports:
        - containerPort: 6379
          name: redis
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      readinessProbe:
        tcpSocket:
          port: redis
        initialDelaySeconds: 20
        timeoutSeconds: 5
        periodSeconds: 3
      livenessProbe:
        tcpSocket:
          port: redis
        initialDelaySeconds: 20
        timeoutSeconds: 5
        periodSeconds: 3
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
          - key: redis-config
            path: redis.conf
