apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.13.0
    helm.sh/chart: argo-cd-7.7.1
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://argocd.o-r.kr

  service.webhook.discord-webhook: |
    url: https://discord.com/api/webhooks/1309414684184805416/VeH2GOqXs2UE7aeOFOxaiJ4yImshGS32G91xGYsIAfq9n6xBDaevGkDkViLVpFkZp-CL
    headers:
    - name: Content-Type
      value: application/json

  template.discord-status: |
    webhook:
      discord-webhook:
        method: POST
        body: |
          {
            "embeds": [
              {
                "title": "Status of {{ .app.metadata.name }}",
                "description": " - Status: **{{ .app.status.operationState.phase }}** + **{{ .app.status.health.status }}**\n - Sync: **{{ .app.status.sync.status }}** \n\n {{ .app.status.sync.revision }}\n [{{ .app.metadata.name }}](https://argocd.o-r.kr/applications/argocd/{{ .app.metadata.name }})",
                "color": "{{ if eq .app.status.operationState.phase "Running" }} 1127128 {{end}} {{ if eq .app.status.operationState.phase "Succeeded" }} 3066993 {{end}} {{ if eq .app.status.operationState.phase "Error" }} 15158332 {{end}} {{ if eq .app.status.operationState.phase "Failed" }} 15158332 {{end}}"
              }
            ]
          }

  template.discord-sync: |
    webhook:
      discord-webhook:
        method: POST
        body: |
          {
            "embeds": [
              {
                "title": "Sync of {{ .app.metadata.name }}",
                "description": "- Sync: **{{ .app.status.sync.status }}**\n\n {{ .app.status.sync.revision }}\n [{{ .app.metadata.name }}](https://argocd.o-r.kr/applications/argocd/{{ .app.metadata.name }})",
                "color": "{{ if eq .app.status.sync.status "Synced" }} 3066993 {{end}} {{ if eq .app.status.sync.status "OutOfSync" }} 15158332 {{end}}"
              }
            ]
          }

  trigger.sync-operation-change: |
    - when: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy' and app.status.sync.status == 'Synced'
      send: [discord-status]
      oncePer: app.status.sync.revision
    - when: app.status.operationState.phase in ['Error']
      send: [discord-status]
      oncePer: app.status.sync.revision
    - when: app.status.operationState.phase in ['Failed']
      send: [discord-status]
      oncePer: app.status.sync.revision

  trigger.sync-check: |
    - when: app.status.sync.status in ['OutOfSync']
      send: [discord-sync]
      oncePer: app.status.sync.revision
